name: Setup and Install
on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      # Install dependencies and run the script
      - name: Install dependencies and run setup script
        run: |
          chmod +x ./deb-sh.sh
          sudo ./deb-setup.sh --setup-device 
