name: Test Setup Scripts

on:
  push:
    branches:
      - "master" # Trigger on push to any branch
  pull_request:
    branches:
      - "master" # Trigger on pull request to any branch

jobs:
  test-arch:
    name: Test Arch Setup Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Arch Linux Container
        uses: addnab/docker-run-action@v3
        with:
          image: manjarolinux/base:latest # Use Manjaro as the Arch-based distro
          options: --privileged
          run: |
            pacman -Syu --noconfirm && pacman -S --noconfirm sudo
            useradd -m github
            echo 'github ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/github
            chmod 0440 /etc/sudoers.d/github
            su - github
      - name: Run Arch Setup Script
        run: |
          chmod +700 ./linux_installer.sh
          sudo ./linux_installer.sh all
        shell: bash

  test-debian:
    name: Debian Setup Script
    runs-on: ubuntu-latest # Use Ubuntu as the Debian-based distro
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ubuntu Container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:latest # Use Ubuntu as the Debian-based distro
          options: --privileged
          run: |
            apt update && apt install -y sudo
            useradd -m github
            echo 'github ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/github
            chmod 0440 /etc/sudoers.d/github
            su - github
      - name: Run Debian Setup Script
        run: |
          chmod +700 ./linux_installer.sh
          sudo ./linux_installer.sh all
        shell: bash

  test-rocky:
    name: Rocky Linux Setup Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Rocky Linux Container
        uses: addnab/docker-run-action@v3
        with:
          image: rockylinux/rockylinux:latest # Use Rocky Linux as the distro
          options: --privileged
          run: |
            yum update -y && yum install -y sudo
            useradd -m github
            echo 'github ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/github
            chmod 0440 /etc/sudoers.d/github
            su - github
      - name: Run Rocky Linux Setup Script
        run: |
          chmod +700 ./linux_installer.sh
          sudo ./linux_installer.sh all
        shell: bash

  test-fedora:
    name: Fedora Setup Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fedora Container
        uses: addnab/docker-run-action@v3
        with:
          image: fedora:latest # Use Fedora as the distro
          options: --privileged
          run: |
            dnf update -y && dnf install -y sudo
            useradd -m github
            echo 'github ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/github
            chmod 0440 /etc/sudoers.d/github
      - name: Run Fedora Setup Script
        run: |
          chmod +700 ./linux_installer.sh
          sudo ./linux_installer.sh all
        shell: bash
