name: Test Linux Installer Script

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test-linux_installer:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, archlinux, rockylinux-8, fedora]
    runs-on: ubuntu-latest  # Use Ubuntu as the base runner to execute Docker commands

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image for the selected OS
        run: |
          docker pull ${{ matrix.os }}:latest  # Pull the respective OS container image

      - name: Run script in Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ matrix.os }}:latest bash -c "
            # Run installation commands 
            chmod +x linux_installer.sh
            sudo ./linux_installer.sh all
          "
