name: Test Linux Installer Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-linux-installer:
    strategy:
      matrix:
        os: [ubuntu-latest, archlinux, centos-latest, fedora-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment for Arch
        if: matrix.os == 'archlinux'
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm base-devel

      - name: Set up environment for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y curl wget zsh

      - name: Set up environment for CentOS
        if: matrix.os == 'centos-latest'
        run: |
          sudo yum update -y
          sudo yum install -y epel-release

      - name: Set up environment for Fedora
        if: matrix.os == 'fedora-latest'
        run: |
          sudo dnf upgrade --refresh -y

      - name: Make script executable
        run: chmod +x Linux-Installer.sh

      - name: Run the script
        run: sudo ./Linux-Installer.sh
